### PR TITLE
Social media toggler added

### LINKED ISSUE #277: [New Feature]: Social media button toggle
### 🎮 feature Request

feature logic and basic description
Currently all of the Social media buttons are visible at all time like shown in picture
this reduce readability sometime
Screenshot (254)

### Point down the features

feature points
Can we make one Toggle button on clicking it all the social media links will be popped out and will be visible to all 
and i will put some smooth transition also
it will make UX better and will look cool in this cool website

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
## PR Description 📜

i have added style and js as well for making toggler to the social media icon
i have added this toggler in 4 pages because in products page there wrer not social buttons even before
Fixes #277 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

https://github.com/ChromeGaming/Community-Page/assets/127788321/15c8172c-9ce6-4891-8c3e-5e6080c6ffbe

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@Manaregr8 @Durgesh4993 
please review this PR
i have done chnages which are needed 
it will not affect other things

**Review by Durgesh4993 — COMMENTED** [review]
Resolve conflict files

**Comment by Yashgabani845** [comment]
@Durgesh4993 sir i have resolved merge conflict

**Comment by Yashgabani845** [comment]
@Durgesh4993 it was just issue of one unmatched paranthesis 
i have fixed it now it is working finale 
please review it again

**Comment by Yashgabani845** [comment]
@Durgesh4993 please checkout the PR i have solved merge conflicts

**Comment by Yashgabani845** [comment]
@Durgesh4993 @Manaregr8 please look over my PR it's been waiting more so long I have done all of the required changes

**Comment by Yashgabani845** [comment]
@Durgesh4993 it's been 4 days can you please look over this  PR

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
