### PR TITLE
fixed responsiveness of about section

### PR DESCRIPTION
**Pull request by Ridhima10**
Hello PA @Manaregr8 
Fixed issue- #331 
Note: space in right of text is still more but it will be fixed in another issue since it is connected with another section

When both of the PR will be merged it will automatically get fixed. THANKYOU.

### CODE REVIEW

**Review by Manaregr8 — CHANGES_REQUESTED** [review]
Its not up to the mark, I assigned it level3 cuz i know it's tough to do so from debugging approach.
Please make changes accordingly, justifying that level.

**Comment by Ridhima10** [comment]
@Manaregr8  It was assigned level 2, in this i have only fixed the about section not anything else, in another PR  which is assigned level 3 in which i have to fix "animation logo responsiveness" i am fixing the whole remaining page and its done too.

**Comment by Ridhima10** [comment]
@Manaregr8 kindly review

**Comment by sanjay-kv** [comment]
image
responsive PR are more than 5. so downgraded few of them

**Pull request merged**
