### PR TITLE
Nav bar contents styling changed

### PR DESCRIPTION
**Pull request by vanisharma2003**
## PR Description 
Fixed issue:#222
Issue assigned - (feature enhancement) Navbar font styling should be changed 

Overall look of the website is good but navbar font styling is not appropriate as per the theme of the website.
So to change this styling I use specific google fonts and add this google font CSS and links at appropriate places.
This will enhance overall look of the website. I add google fonts link to each and every page with .html extension  so that whenever user clicks to any page , the font styling would remain same.

<hr>
 
## Mark the task you have completed ✅

- [X ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X ] I have performed a self-review of my own code or work.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generates no new warnings.
- [X ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X ] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by vanisharma2003** [comment]
WhatsApp Image 2024-05-29 at 13 38 15_93593617

**Comment by vanisharma2003** [comment]
WhatsApp Image 2024-05-29 at 13 38 26_a9909fdb

**Comment by Manaregr8** [comment]
hi @vanisharma2003,

Can you mention the issue assigned?

**Comment by vanisharma2003** [comment]
> hi @vanisharma2003,
> 
> Can you mention the issue assigned?
This issue is assigned to me 
What are you trying to say??
I don't understand 😊

**Comment by vanisharma2003** [comment]
> hi @vanisharma2003,
> 
> Can you mention the issue assigned?

I am mentioned the issue in PR description

**Review by Durgesh4993 — COMMENTED** [review]
Please resolve conflict files

**Comment by vanisharma2003** [comment]
> Please resolve conflict files

Okiee

**Comment by vanisharma2003** [comment]
> Please resolve conflict files

Could you please provide me an extra day to resolve this?
As tomorrow will be  my end sem exam

**Comment by Manaregr8** [comment]
> > Please resolve conflict files
> 
> Could you please provide me an extra day to resolve this? As tomorrow will be my end sem exam



> > Please resolve conflict files
> 
> Could you please provide me an extra day to resolve this? As tomorrow will be my end sem exam

Take your time,

However, please note that your files are conflicting because your forked repository is outdated. Kindly update your forked repository as Express and Node have been added to it. Once you update your repository, your files will no longer conflict. Refer to the README document for any further assistance.

**Comment by vanisharma2003** [comment]
> > > Please resolve conflict files
> > 
> > Could you please provide me an extra day to resolve this? As tomorrow will be my end sem exam
> 
> 
> 
> > > Please resolve conflict files
> > 
> > Could you please provide me an extra day to resolve this? As tomorrow will be my end sem exam
> 
> Take your time,
> 
> However, please note that your files are conflicting because your forked repository is outdated. Kindly update your forked repository as Express and Node have been added to it. Once you update your repository, your files will no longer conflict. Refer to the README document for any further assistance.

Okiee sure sir 
Thanks a lot 😊

**Pull request closed without merging**
