### PR TITLE
Navbar Content Style Update

### PR DESCRIPTION
**Pull request by vanisharma2003**
## PR Description 📜
issue number:#222
issue-Feature enhancement- Navbar styling should be changed.
Overall look of the website is very good but navbar content styling and font style is not as the theme of the website. Navbar is the very first thing a user will notice so it should be based on the theme of the website. So I use a good font and apply some CSS styling to change the font styling of the Navbar content.
I am also attaching images of the changes that I have created.

<hr>
 
## Mark the task you have completed ✅

- [X ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generates no new warnings.
- [ X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ X] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by vanisharma2003** [comment]
Screenshot 2024-06-02 111251

**Comment by vanisharma2003** [comment]
Screenshot 2024-06-02 111309

**Comment by Manaregr8** [comment]
Hi @vanisharma2003,

Its a nice font but navbar responsiveness is compromised for some screens. You can fix that with media queries update them accordingly and its done.

Thank You

**Comment by vanisharma2003** [comment]
Okiee I will fix this 😊

**Comment by vanisharma2003** [comment]
I have recently made a commit update. Now, the issue is fixed. Navbar responsiveness is no more compromised.
Screenshot 2024-06-02 213845

**Comment by vanisharma2003** [comment]
Pls update

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Work on responsiveness for mobiles also

**Review by Manaregr8 — APPROVED** [review]

**Pull request merged**
