### PR TITLE
Update script.js

### LINKED ISSUE #358: [Bug]: Issues with Fetching and Displaying GitHub Contributors
### Give a brief about the bug ✍️

The code fetching and displaying GitHub contributors has several issues, including a hardcoded page parameter, inefficient DOM updates, and global variable scope problems.

### What is the expected behavior? 🤔

- The function `getContributors` should correctly fetch contributors across multiple pages.
- The contributors should be sorted and displayed in the correct order.
- The search functionality should work without undefined variables.
- The DOM should be updated efficiently to improve performance.

### Provide step by step information to reproduce the bug 📄

1. Hardcoded Page Parameter

- Open the code and locate the `getContributors` function.
- Notice that the `page` parameter in the fetch URL is hardcoded to 1.

2. Inefficient DOM Updates

- Observe the DOM update logic within the `window.onload` function.
- Notice the repeated DOM manipulations without using `DocumentFragment`.

3. Undefined data Variable in Search

- Check the `searchResult.addEventListener` function.
- Notice the `data` variable is not defined globally, causing errors when the search input is used.

4. Inconsistent Dark Mode Toggle Event Listeners

- Examine the event listeners for dark mode toggle.
- Notice duplicated event listeners and possible issues with theme toggling.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Swapnilden**
## PR Description 📜

This PR addresses several issues related to the fetching and displaying of GitHub contributors. The following improvements have been made:

- Corrected the hardcoded `page` parameter and added pagination to fetch all contributors.
- Optimized DOM updates using `DocumentFragment` to enhance performance.
- Ensured the `data` variable is globally accessible for the search functionality.
- Consolidated and streamlined event listeners, especially for dark mode toggling and Discord popup handling.
Fixes #358 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [] I have added screenshot for review.

<hr>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Manaregr8 — CHANGES_REQUESTED** [review]
Why did you removed Rating function in your script.js and its related functions....? it leads to non functioning Rate us button 
Please explain

**Review by Swapnilden — COMMENTED** [review]
@Manaregr8 I appreciate your feedback regarding the recent changes I made to the script.js file. The removal of the Rating function and its related functions was an unintentional oversight during the process of updating the contributors' functionality.

Here's a more explanation of what happened:

- Focus on Contributors:

My primary task was to enhance how contributors are fetched from the GitHub API and displayed on the webpage. This involved updating the functions that retrieve and present the list of contributors.

- Unintentional Removal:

In the process of streamlining and cleaning up the code, I mistakenly removed some functions related to the rating feature. These functions were responsible for updating the slider value, handling feedback submissions, and managing the "Rate us" modal.

- Impact on the "Rate us" Button:

The removal of these functions caused the "Rate us" button to stop working because the essential code supporting its functionality was missing. This was an unintended consequence of the changes I made.

- Resolution:

I recognize the importance of the "Rate us" feature and promptly re-integrate the removed functions to ensure it works correctly.

I apologize for any inconvenience caused and will ensure that such issues are avoided in the future. Thank you for bringing this to my attention.

**Review by Manaregr8 — APPROVED** [review]
Nicelly Donee!!

**Comment by Swapnilden** [comment]
@Manaregr8 thanks for compliment!!

**Pull request merged**
