### PR TITLE
solve discord button that text color changed in light mode to white c…

### LINKED ISSUE #188: [Bug]: Burger Menu is not visible in light mode responsive
### Give a brief about the bug ✍️

@GameSphere-MultiPlayer

here when we toggle to responsive mode, the burger menu icon is not visible in light mode

### What is the expected behavior? 🤔

Description

you can check this out this is light mode image
image

dark mode image with toggle menu
image

### Provide step by step information reproduce the bug 📄

Description

we can change color of toggle menu in light mode

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by dhruv8433**
…olor

@GameSphere-MultiPlayer

## PR Description 📜
Burger Menu is not visible in light mode responsive #188

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #188

<hr>
 
## Mark the task you have completed ✅
- added color for burger menu so it visible in light mode too
- chnage color of discord join button because it also chaneg to white in light mode

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
see discord button text is not visible i added bg color so it visible in both light and dark mode

image

likt this

image

and burger menu not visible in light mode

image

so i change color of burger menu in light mode

image

please check this and merge it

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Manaregr8** [comment]
It will look nice in green color background like Github's green and black buttons for comment.
use color #09B43A 

Thank You

**Comment by dhruv8433** [comment]
@Manaregr8 

as you say, i  updated background color of discord button
image

**Comment by dhruv8433** [comment]
Hey @Manaregr8 ,
i dont see comment btn in your web ,can you help me ?

**Review by Durgesh4993 — APPROVED** [review]
resolve Conflicting files

**Comment by dhruv8433** [comment]
@Durgesh4993 

now you can merge it

**Comment by dhruv8433** [comment]
@Durgesh4993 

please check this i resolve all conflicts
now you can merge it

**Comment by dhruv8433** [comment]
@Durgesh4993

please check this 
as you say, i resolve all conflicts and now you can merge it

**Comment by Manaregr8** [comment]
> Hey @Manaregr8 , i dont see comment btn in your web ,can you help me ?

I was referring to GitHub's comment button. However, the button you created is exactly what I was mentioning ;)

**Comment by Manaregr8** [comment]
> @Durgesh4993
> 
> please check this as you say, i resolve all conflicts and now you can merge it

"Hey, nice work!

However, there's one problem: the repository has been updated, and your version is not. Please update it, and I will merge it."

Let me know if you need any further adjustments!

**Comment by dhruv8433** [comment]
@Manaregr8 

i updated repo with latest changes code
now you can merge it

**Comment by dhruv8433** [comment]
@Durgesh4993 

Thank you :)

**Pull request merged**
