### PR TITLE
Hover Effect to Footer added

### LINKED ISSUE #221: [New Feature]: Hover effect to footer
### 🎮 feature Request

The footer can look even better if it has hover effect to the links and also if the cursor changes to pointer when it hovers over the first links of the footer.

image

### Point down the features

features i would add:

- Hover effect to the footer links.
- cursor fix to the first links in the footer.
- make share icon interactive with hover effect of background

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by chaanakyaaM**
## PR Description 📜

I have added to hover effect to the footer links and also corrected the cursor for the top most links, and also added the hover effect to the Share button.

Fixes #221 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot (44)
Screenshot (45)

<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by chaanakyaaM** [comment]
Kindly let me know if there are any changes to be made.

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Please resolve conflict files

**Comment by chaanakyaaM** [comment]
ok

**Comment by chaanakyaaM** [comment]
conflicts are resolved once view the

https://github.com/ChromeGaming/Community-Page/pull/259 PR

**Pull request closed without merging**
