### PR TITLE
Improved the responsiveness

### LINKED ISSUE #264: [Bug]: Improve the responsiveness
### Give a brief about the bug ✍️

In mobile devices (small devices), the responsiveness is not that great. The logo goes out of display, as well as the Social icons overlap the other content. This makes the webpage clumsy.

Screenshot 2024-05-31 102200

### What is the expected behavior? 🤔

THe webpage UI should be clean enough and the content should be clearly visible, along with the icons properly aligned so as to provide a great User Experience.

### Provide step by step information to reproduce the bug 📄

1. Open the webpage.
2. Go to inspect.
3. Lower the width of the screen to that of small screens.
4. You'll get to see the issue.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
## PR Description 📜

- The logo is now centralized, and visible even on smaller devices, and it doesn't move out of the screen on lowering the width of the screen
- The social icons no more overlap the content, and the content is now clearly visible
- In smaller screens, the social icons have been moved to the navbar, and it opens when the user opens the menu

Fixes #264 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot 2024-06-01 113921

Screenshot 2024-06-01 113933

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@Sambit-Mondal Add a demo video of all pages

**Comment by Sambit-Mondal** [comment]
Okay Sir, doing it in a bit. I'm outside right now.

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Sir, here's the demo for all the pages:

https://github.com/ChromeGaming/Community-Page/assets/138088550/e8715327-7ddb-40d8-bf77-970434c09d3d

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Resolve conflict files

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Solved the conflicts Sir.

**Comment by Sambit-Mondal** [comment]
Thank you Sir @Durgesh4993!

**Pull request merged**
