### PR TITLE
Suggestion/ Feedback form

### PR DESCRIPTION
**Pull request by ananyag309**
Issue: #290 

@Manaregr8 created a suggestion/feedback form which can help user directly interact through the community page. The form background can be changed, it is accepting response. Please check 
 

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
formmmmmmm

--- 
<br>

### CODE REVIEW

**Comment by ananyag309** [comment]
@Manaregr8 sir please let me know for further changes, moreover add gssoc and level label 2 and assignes my name.
thank you

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Add a demo vedio, and create a button on home screen to get the form

**Comment by ananyag309** [comment]
@Durgesh4993 sir the background can be replaced by some gaming gif. right now i have used gradient

https://github.com/ChromeGaming/Community-Page/assets/145869907/26f61519-bec2-4cca-8b0f-7c1b08d76ed1

**Comment by Durgesh4993** [comment]
@ananyag309 Is there are any issue, why css is not working

**Comment by ananyag309** [comment]
@Durgesh4993 can you please tell what's happening because it's working on mine

https://github.com/ChromeGaming/Community-Page/assets/145869907/c388cb33-e146-4613-bc14-f67c860535d9

**Comment by Durgesh4993** [comment]
@ananyag309 Show whole website how it's work

**Comment by Durgesh4993** [comment]
You are showing just one module

**Comment by ananyag309** [comment]
@Durgesh4993 it's here

https://github.com/ChromeGaming/Community-Page/assets/145869907/3782ecfc-a84b-4cad-aa19-287ca4caac27

**Comment by Manaregr8** [comment]
Hi @ananyag309 ,

Sorry for the delay caused by my ongoing exams. The issue with your code is that you added it directly to index.html. The entire site is now undergoing a change in framework, so please follow the README to open the website locally on your server. Also, please fork the latest version. If you have any doubts or are unable to find the correct way, tag me in this conversation again, and I will arrange a Google Meet for you.

Thank you.

**Comment by ananyag309** [comment]
ok i will be correcting it soon

**Pull request closed without merging**
