### PR TITLE
Fixed top navbar

### LINKED ISSUE #108: Fixed top Navbar
### 🎮 feature Request

I would like to fix the top navbar so that it would be visible even upon scroll.

### Select program in which you are contributing

GSSOC

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Priya-49**
## PR Description 📜
Fixed top navbar to make it visible even with the scroll.
Fixes #108 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
Screenshot 2024-05-29 132655

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Priya-49** [comment]
@Durgesh4993 
Due to some issues I need to close my previous PR (#120 ). This PR is about the same issue as before.
Screenshot 2024-05-29 132655

**Comment by Manaregr8** [comment]
> @Durgesh4993 Due to some issues I need to close my previous PR (#120 ). This PR is about the same issue as before. Screenshot 2024-05-29 132655


Great effort! Just make a few adjustments for responsiveness on mobile screens, otherwise, there's nothing else to change. Good job, thank you!

**Comment by Priya-49** [comment]
@Manaregr8 
I have made the requested changes.

**Review by Durgesh4993 — COMMENTED** [review]
Please resolve conflict files

**Comment by Priya-49** [comment]
@Durgesh4993
I couldn't resolve the conflicts..could u help me out..
Screenshot 2024-05-30 124212

**Comment by Durgesh4993** [comment]
You need to reclone repo again

**Comment by Durgesh4993** [comment]
Then update your code because, I have changes some major

**Comment by Priya-49** [comment]
The instructions for creating a PR must be updated since the repo name is changed. Due to this the upstream command doesn't work.

**Pull request closed without merging**
