### PR TITLE
fixed

### PR DESCRIPTION
**Pull request by Ridhima10**
Hello Pa @Manaregr8 
Issue resolved- #367 
Screenshot 2024-07-07 150038

### CODE REVIEW

**Comment by Ridhima10** [comment]
@Manaregr8  kindly review this

**Review by Manaregr8 — APPROVED** [review]
nicelly done

**Comment by Manaregr8** [comment]
@Ridhima10 Please resolve conflicting files.

**Comment by Ridhima10** [comment]
@Manaregr8 done

**Pull request merged**
