### PR TITLE
Added animated cursor functionality

### PR DESCRIPTION
**Pull request by Ridhima10**
Hello PA @Manaregr8 
Issue resolved- #320 

Kindly review and merge

### CODE REVIEW

**Comment by Ridhima10** [comment]
@Manaregr8 kindly review it

**Comment by Manaregr8** [comment]
> @Manaregr8 kindly review it

Amazing work @Ridhima10, but some files are conflicting please check them. than will merge this one.

**Comment by Ridhima10** [comment]
@Manaregr8 Its done :)

**Review by Manaregr8 — CHANGES_REQUESTED** [review]
Cursor animation in product page is not working, its working for all rest of the pages.

**Comment by Ridhima10** [comment]
https://github.com/ChromeGaming/Community-Page/assets/85826117/b109c578-26f8-4ff0-a7f9-8db134ece1de

@Manaregr8 its working

**Pull request merged**
