### PR TITLE
Added footer to contribute,play,product page

### LINKED ISSUE #216: [New Feature]: Adding footer section in product , play games ,contribute pages
### 🎮 feature Request

Adding footer section in product , play games ,contribute pages as currently the don't have footer section.

### Point down the features

Adding footer section in product , play games ,contribute pages
image

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by agastya3636**
## PR Description 📜

Added footer to contribute,play,product page
Fixes #216 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

image
image
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
delete product.html

**Comment by agastya3636** [comment]
I have to delete footer or page

**Comment by agastya3636** [comment]
Done

**Review by Durgesh4993 — COMMENTED** [review]
Please resolve conflict files

**Pull request closed without merging**
