### PR TITLE
Added a progress bar on every page .

### LINKED ISSUE #383: [New Feature]: Add a progress bar on the top of the navbar .
### 🎮 feature Request

I want to add a progress bar on the top of the navbar .

### Point down the features

This progress bar  progresses as the page scrolls up and down .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by meetarora10**
## PR Description 📜
Added a progress bar which matches the UI of website, on every page in the website which will progress as the page scrolls up and down .
Fixes #383

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

https://github.com/user-attachments/assets/f3a708d0-3537-415e-baf4-5e2bff810f0f

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Manaregr8 — APPROVED** [review]
Nicelly Done!

**Comment by meetarora10** [comment]
Please give appropriate labels and kindly assign me .
Thank you .

**Comment by Manaregr8** [comment]
> Please give appropriate labels and kindly assign me . Thank you .

I was just giving that...but still thanks for reminding.

good day

**Comment by meetarora10** [comment]
> > Please give appropriate labels and kindly assign me . Thank you .
> 
> I was just giving that...but still thanks for reminding.
> 
> good day

Thank you @Manaregr8

**Pull request merged**
