### PR TITLE
UI Enhanced - Navbar

### LINKED ISSUE #225: [Bug]: Search bar overlapping
### Give a brief about the bug ✍️

The search bar is overlapping the text in the navbar .

### What is the expected behavior? 🤔

Screenshot (485)
Screenshot (486)

### Provide step by step information to reproduce the bug 📄

 I will make sure to make it better and remove the overlappings.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by sharmi4590**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #225 

Since there were many overlappings in the navbar , I changed the whole navbar and now it is responsive and UI has been enhanced, removed overlappings.
<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

https://github.com/ChromeGaming/Community-Page/assets/102676949/abb12725-8f86-4b81-b768-e6e145dbe89e

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Please bold the logo name and increase the font size also

**Comment by sharmi4590** [comment]
Done.
Screenshot 2024-05-31 204802

**Comment by sharmi4590** [comment]
Done.
Screenshot 2024-05-31 210809

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Pull request merged**
